export const mimeType = new Map<string, string>([
  [".ico", "image/x-icon"],
  [".html", "text/html"],
  [".js", "text/javascript"],
  [".json", "application/json"],
  [".css", "text/css"],
  [".png", "image/png"],
  [".jpeg", "image/jpeg"],
  [".gif", "image/gif"],
  [".jpg", "image/jpeg"],
  [".wav", "audio/wav"],
  [".mp3", "audio/mpeg"],
  [".svg", "image/svg+xml"],
  [".pdf", "application/pdf"],
  [".zip", "application/zip"],
  [".doc", "application/msword"],
  [".eot", "application/vnd.ms-fontobject"],
  [".ttf", "application/x-font-ttf"],
  [".xhtml", "application/xhtml+xml"],
]);
